server:
  port: 8080

spring:
  rabbitmq:
    username: root
    password: root
    virtual-host: /
    host: 127.0.0.1
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true # 开启重试
          max-attempts: 3 # 最大重试次数
          initial-interval: 2000ms  # 重试间隔时间